### ISSUE TITLE
Performance on THUMOS14 shown in README

### ISSUE THREAD

**Issue by zhenzhiwang** [Alvin-Zeng/DRN#2]
Hello, thank you for sharing the code!

From the DRN paper, I know DRN follows anchor-free methods and achieves great performance on 3 temporal grounding datasets. By the similar architecture, I believe that DRN can also achieve a good result in temporal action localization task, but there is no R@1 IoU=0.5 metric in temporal action localization task. I want to know whether you mean mAP IoU=0.5 or the metric like AR@100 in temporal action proposal task?

P.S. It will be better if you can share the code for action localization/proposal tasks in THUMOS14 dataset.

Thank you again for sharing the code of this inspiring work!

**Comment by Alvin-Zeng** [comment]
Sorry, it should be a typo in README (we have fixed it). We did not conduct experiments on the temporal action localization (TAL) task. It would be interesting to extend our method to the TAL task.

**Comment by zhenzhiwang** [comment]
Thank you for your response, I believe that drn can also make a good performance on TAL task.
